# tasks file for tigervnc-server
- name: Install TigerVNC-server package
  package:
    name: tigervnc-server
    state: present
  notify: restart vncserver
  tags:
    - tigervnc-server

- name: copy vnc server config
  template:
    src: templates/vncservers.j2
    dest: /etc/sysconfig/vncservers
    owner: root
    group: root
    mode: 0644
  notify: restart vncserver
  tags:
    - tigervnc-server

- name: create a directory .vnc
  file:
    path: "~{{ VNC_USER }}/.vnc"
    owner: "{{ VNC_USER }}"
    group: "{{ VNC_USER }}"
    state: directory
  tags:
    - tigervnc-server

- name: prepare a file .vnc/passwd
  file:
    path: "~{{ VNC_USER }}/.vnc/passwd"
    owner: "{{ VNC_USER }}"
    group: "{{ VNC_USER }}"
    mode: 0600
    state: touch
  notify: restart vncserver
  tags:
    - tigervnc-server

- name: set password for vnc user
  command: "echo -n {{ VNC_PASSWORD }} | vncpasswd -f > ~{{ VNC_USER }}/.vnc/passwd"
  become: yes
  become_user: "{{ VNC_USER }}"
  notify: restart vncserver
  tags:
    - tigervnc-server

- name: enable vncserver service
  service:
    name: "vncserver@{{ VNC_DISPLAY }}.service"
    enabled: yes
  tags:
    - tigervnc-server
